services:
  telephoneapp:
    image: telephoneapp:1.1
    ports:
      - "8080:8080"
  consul:
    image: hashicorp/consul
    build: 
      context: telephoneapi/
    ports:
      - "8500:8500"
      - "8600:8600/udp"
  telephoneapi:
    image: telephoneapi:1.1
    ports:
      - "7000:8080"
    depends_on:
      - consul
